import fs from 'node:fs'
import path from 'node:path'

// 注意路径可能需要根据实际 node_modules 调整
const themesDir = path.resolve(process.cwd(), 'node_modules/@shikijs/themes/dist')
const files = fs.readdirSync(themesDir)

const themes = files
    .filter(f => f.endsWith('.mjs') && !f.endsWith('.d.mts') && f !== 'index.mjs')
    .map(f => f.replace('.mjs', ''))

const imports = themes.map((theme, i) => `import theme${i} from '@shikijs/themes/${theme}'`).join('\n')
const exports = `export const allThemes = [\n${themes.map((_, i) => `  (theme${i} as any).default || theme${i}`).join(',\n')}\n]`

const content = `// Generated by scripts/generate-all-themes.ts
${imports}

${exports}
`

fs.writeFileSync(path.resolve(process.cwd(), 'src/all-themes.ts'), content)
console.log(`Generated src/all-themes.ts with ${themes.length} themes`)
