import fs from 'node:fs'
import path from 'node:path'

const langsDir = path.resolve(process.cwd(), 'node_modules/@shikijs/langs/dist')
const files = fs.readdirSync(langsDir)

const langs = files
    .filter(f => f.endsWith('.mjs') && !f.endsWith('.d.mts') && f !== 'index.mjs')
    .map(f => f.replace('.mjs', ''))

const imports = langs.map((lang, i) => `import lang${i} from '@shikijs/langs/${lang}'`).join('\n')
const exports = `export const allLangs = [\n${langs.map((_, i) => `  (lang${i} as any).default || lang${i}`).join(',\n')}\n]`

const content = `// Generated by scripts/generate-all-langs.ts
${imports}

${exports}
`

fs.writeFileSync(path.resolve(process.cwd(), 'src/all-langs.ts'), content)
console.log(`Generated src/all-langs.ts with ${langs.length} languages`)
