// Generated by scripts/generate-all-themes.ts
import theme0 from '@shikijs/themes/catppuccin-latte'
import theme1 from '@shikijs/themes/kanagawa-dragon'
import theme2 from '@shikijs/themes/snazzy-light'
import theme3 from '@shikijs/themes/one-light'
import theme4 from '@shikijs/themes/andromeeda'
import theme5 from '@shikijs/themes/vitesse-dark'
import theme6 from '@shikijs/themes/night-owl'
import theme7 from '@shikijs/themes/tokyo-night'
import theme8 from '@shikijs/themes/gruvbox-light-medium'
import theme9 from '@shikijs/themes/dark-plus'
import theme10 from '@shikijs/themes/one-dark-pro'
import theme11 from '@shikijs/themes/laserwave'
import theme12 from '@shikijs/themes/kanagawa-lotus'
import theme13 from '@shikijs/themes/dracula-soft'
import theme14 from '@shikijs/themes/material-theme-darker'
import theme15 from '@shikijs/themes/everforest-dark'
import theme16 from '@shikijs/themes/material-theme'
import theme17 from '@shikijs/themes/aurora-x'
import theme18 from '@shikijs/themes/dracula'
import theme19 from '@shikijs/themes/solarized-dark'
import theme20 from '@shikijs/themes/monokai'
import theme21 from '@shikijs/themes/light-plus'
import theme22 from '@shikijs/themes/solarized-light'
import theme23 from '@shikijs/themes/red'
import theme24 from '@shikijs/themes/ayu-dark'
import theme25 from '@shikijs/themes/github-light-default'
import theme26 from '@shikijs/themes/material-theme-palenight'
import theme27 from '@shikijs/themes/catppuccin-frappe'
import theme28 from '@shikijs/themes/catppuccin-macchiato'
import theme29 from '@shikijs/themes/catppuccin-mocha'
import theme30 from '@shikijs/themes/vitesse-light'
import theme31 from '@shikijs/themes/gruvbox-light-hard'
import theme32 from '@shikijs/themes/rose-pine-moon'
import theme33 from '@shikijs/themes/slack-dark'
import theme34 from '@shikijs/themes/material-theme-ocean'
import theme35 from '@shikijs/themes/min-light'
import theme36 from '@shikijs/themes/poimandres'
import theme37 from '@shikijs/themes/vitesse-black'
import theme38 from '@shikijs/themes/slack-ochin'
import theme39 from '@shikijs/themes/gruvbox-dark-medium'
import theme40 from '@shikijs/themes/houston'
import theme41 from '@shikijs/themes/gruvbox-dark-hard'
import theme42 from '@shikijs/themes/kanagawa-wave'
import theme43 from '@shikijs/themes/plastic'
import theme44 from '@shikijs/themes/synthwave-84'
import theme45 from '@shikijs/themes/github-light'
import theme46 from '@shikijs/themes/material-theme-lighter'
import theme47 from '@shikijs/themes/rose-pine-dawn'
import theme48 from '@shikijs/themes/gruvbox-dark-soft'
import theme49 from '@shikijs/themes/github-light-high-contrast'
import theme50 from '@shikijs/themes/vesper'
import theme51 from '@shikijs/themes/github-dark'
import theme52 from '@shikijs/themes/min-dark'
import theme53 from '@shikijs/themes/gruvbox-light-soft'
import theme54 from '@shikijs/themes/nord'
import theme55 from '@shikijs/themes/everforest-light'
import theme56 from '@shikijs/themes/rose-pine'
import theme57 from '@shikijs/themes/github-dark-high-contrast'
import theme58 from '@shikijs/themes/github-dark-dimmed'
import theme59 from '@shikijs/themes/github-dark-default'

export const allThemes = [
  (theme0 as any).default || theme0,
  (theme1 as any).default || theme1,
  (theme2 as any).default || theme2,
  (theme3 as any).default || theme3,
  (theme4 as any).default || theme4,
  (theme5 as any).default || theme5,
  (theme6 as any).default || theme6,
  (theme7 as any).default || theme7,
  (theme8 as any).default || theme8,
  (theme9 as any).default || theme9,
  (theme10 as any).default || theme10,
  (theme11 as any).default || theme11,
  (theme12 as any).default || theme12,
  (theme13 as any).default || theme13,
  (theme14 as any).default || theme14,
  (theme15 as any).default || theme15,
  (theme16 as any).default || theme16,
  (theme17 as any).default || theme17,
  (theme18 as any).default || theme18,
  (theme19 as any).default || theme19,
  (theme20 as any).default || theme20,
  (theme21 as any).default || theme21,
  (theme22 as any).default || theme22,
  (theme23 as any).default || theme23,
  (theme24 as any).default || theme24,
  (theme25 as any).default || theme25,
  (theme26 as any).default || theme26,
  (theme27 as any).default || theme27,
  (theme28 as any).default || theme28,
  (theme29 as any).default || theme29,
  (theme30 as any).default || theme30,
  (theme31 as any).default || theme31,
  (theme32 as any).default || theme32,
  (theme33 as any).default || theme33,
  (theme34 as any).default || theme34,
  (theme35 as any).default || theme35,
  (theme36 as any).default || theme36,
  (theme37 as any).default || theme37,
  (theme38 as any).default || theme38,
  (theme39 as any).default || theme39,
  (theme40 as any).default || theme40,
  (theme41 as any).default || theme41,
  (theme42 as any).default || theme42,
  (theme43 as any).default || theme43,
  (theme44 as any).default || theme44,
  (theme45 as any).default || theme45,
  (theme46 as any).default || theme46,
  (theme47 as any).default || theme47,
  (theme48 as any).default || theme48,
  (theme49 as any).default || theme49,
  (theme50 as any).default || theme50,
  (theme51 as any).default || theme51,
  (theme52 as any).default || theme52,
  (theme53 as any).default || theme53,
  (theme54 as any).default || theme54,
  (theme55 as any).default || theme55,
  (theme56 as any).default || theme56,
  (theme57 as any).default || theme57,
  (theme58 as any).default || theme58,
  (theme59 as any).default || theme59
]
